import styles from './page.module.css'

export default function Home() {

  return (
    <main className={styles.main}>
      <div className={styles.description}>
        <h1>
          Welcome to your AI presentation!
        </h1>
        <p>Enjoy a fully automated presentation generated by your friendly AI.</p>
        <a className={styles.link} href='/presentation'>Click here to view the presentation.</a>
      </div>
    </main>
  )
}
